name: Autograding Tests
on:
  repository_dispatch:
  workflow_dispatch:
permissions:
  checks: write
  actions: read
  contents: read


jobs:
  autograding-tests:
    if: github.actor != 'github-classroom[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check file exists
        id: file
        run: |
          test -f .github/workflows/outputs.yaml && echo "success" || (echo "fail" && exit 1)

      - name: Check input build-status definition
        id: input
        run: |
          if grep -q "build-status:" .github/workflows/outputs.yaml &&
             grep -q "type: choice" .github/workflows/outputs.yaml &&          
             grep -q "success" .github/workflows/outputs.yaml &&
             grep -q "failure" .github/workflows/outputs.yaml &&
             grep -q "Choose the build status for the demo" .github/workflows/outputs.yaml; then
            echo "success"
          else
            echo "fail"
            exit 1
          fi

      - name: Check GITHUB_OUTPUT is printed
        id: output_path
        run: |
          grep -q "GITHUB_OUTPUT" .github/workflows/outputs.yaml && echo "success" || (echo "fail" && exit 1)
    
      - name: Check build job outputs
        id: job_outputs
        run: |
          grep -q "outputs:" .github/workflows/outputs.yaml &&
          grep -q "build-status:.*steps.build.outputs.status" .github/workflows/outputs.yaml && echo "success" || (echo "fail" && exit 1)

      - name: Check deploy job depends on build
        id: deploy_needs
        run: |
          grep -q "needs: build" .github/workflows/outputs.yaml && echo "success" || (echo "fail" && exit 1)

  
 
