name: Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        description: "Choose the build status for the demo"
        required: true  
        type: choice  
        default: success
        options:
          - success
          - failure

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo $GITHUB_PATH 

      - name: Build
        id: build
        run: echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"  


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && inputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: echo "Deploying"
